/**
 * Message types for page ↔ content script communication
 * These strings are used in postMessage calls between the page context and content script context
 */
const CSH_MESSAGE_TYPES = {
  // Page → Content Script
  SAVE_POINTS: 'CSH_SAVE_POINTS',
  TOUCH_POINTS: 'CSH_TOUCH_POINTS',
  TOUCH_STUDENT_NAME: 'CSH_TOUCH_STUDENT_NAME',
  CLEAR_QUEUED_STUDENT: 'CSH_CLEAR_QUEUED_STUDENT',
  START_GROUPS_CHECK: 'CSH_START_GROUPS_CHECK',
  GROUP_TRIPLET_CACHE_UPSERT: 'CSH_GROUP_TRIPLET_CACHE_UPSERT',
  GROUP_TRIPLET_CACHE_LOOKUP: 'CSH_GROUP_TRIPLET_CACHE_LOOKUP',
  TRIGGER_GROUP_MATCH_GRADING_STATUS: 'CSH_TRIGGER_GROUP_MATCH_GRADING_STATUS',

  // Content Script → Page
  UPDATE_SETTINGS: 'CSH_UPDATE_SETTINGS',
  GROUP_TRIPLET_CACHE_LOOKUP_RESULT: 'CSH_GROUP_TRIPLET_CACHE_LOOKUP_RESULT',

  // Content Script/Worker/Groups page routing
  GROUPS_GET_PENDING_CONTEXT: 'CSH_GROUPS_GET_PENDING_CONTEXT',
  GROUPS_CHECK_COMPLETE: 'CSH_GROUPS_CHECK_COMPLETE',
  GROUPS_CHECK_RESULT: 'CSH_GROUPS_CHECK_RESULT',
  GROUPS_CHECK_GRADING_STATUS: 'CSH_GROUPS_CHECK_GRADING_STATUS',
  CLOSE_SPEEDGRADER_TAB: 'CSH_CLOSE_SPEEDGRADER_TAB',
  CLICK_QUEUE_COMPLETE_AFTER_COMMENT: 'CSH_CLICK_QUEUE_COMPLETE_AFTER_COMMENT',

  // Popup → SpeedGrader content script
  POPUP_JUMP_TO_STUDENT_GROUPS: 'CSH_POPUP_JUMP_TO_STUDENT_GROUPS',
  // Page → Dispatcher (submission operations)
  SUBMISSION_GET_TEXT: 'CSH_SUBMISSION_GET_TEXT',
  SUBMISSION_APPLY_HIGHLIGHTS: 'CSH_SUBMISSION_APPLY_HIGHLIGHTS',
  SUBMISSION_SCROLL_INTO_VIEW: 'CSH_SUBMISSION_SCROLL_INTO_VIEW',

  // Dispatcher → Page (submission operation responses)
  SUBMISSION_GET_TEXT_RESPONSE: 'CSH_SUBMISSION_GET_TEXT_RESPONSE',
  SUBMISSION_APPLY_HIGHLIGHTS_RESPONSE: 'CSH_SUBMISSION_APPLY_HIGHLIGHTS_RESPONSE',
  SUBMISSION_SCROLL_INTO_VIEW_RESPONSE: 'CSH_SUBMISSION_SCROLL_INTO_VIEW_RESPONSE',

  // Dispatcher ↔ iframe content (submission iframe protocol)
  IFRAME_SUBMISSION_REQUEST: 'CSH_IFRAME_SUBMISSION_REQUEST',
  IFRAME_SUBMISSION_RESPONSE: 'CSH_IFRAME_SUBMISSION_RESPONSE',
};
